networks:
    sail:
        driver: bridge
services:
    backend:
        container_name: backend
        build:
            context: ./backend/vendor/laravel/sail/runtimes/8.2
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: ms-arjos/laravel-sail-8.2
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - ${APP_PORT:-8000}:80
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        volumes:
            - './backend/:/var/www/html'
            - '.env:/var/www/html/.env'
        working_dir: /backend
        networks:
            - sail
#         depends_on:
#             - mysql
    # Nginx
    proxy:
        image: nginx:1.25
        container_name: proxy
        ports:
            - 8001:80
        volumes:
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - backend
        networks:
            - sail
    # DB MySQL
    database:
        image: mariadb
        container_name: database
        restart: unless-stopped
        environment:
            MYSQL_USER: ${DB_USERNAME-laravel_vault}
            MYSQL_PASSWORD: ${DB_PASSWORD-laravel_vault_pwd}
            MYSQL_DATABASE: ${DB_DATABASE-laravel_vault}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD-laravel_vault_pwd}
        volumes:
            - ./database/mysql:/var/lib/mysql
        networks:
            - sail

    # PHPMyAdmin
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        restart: always
        depends_on:
            - database
        environment:
            PMA_HOST: database
            PMA_PORT: ${DB_PORT-3306}
            PMA_ARBITRARY: 1
            PMA_CONTROLHOST: database
            PMA_CONTROLPORT: ${DB_PORT-3306}
        volumes:
            - ./docker/php/custom.ini:/usr/local/etc/php/conf.d/uploads.ini
        ports:
            - ${PMA_PORT-8888}:80
        networks:
            - sail

    # Optional Installations
    # Redis (OPTIONAL)
    cache:
        image: redis:7
        container_name: cache
        networks:
            - sail
